#! /usr/bin/env bash

set -euo pipefail

ls *.raw >& /dev/null || (echo "No stream files here."; exit 2)

PFX=$(basename $PWD)
DIR=${PFX}-STREAM
mkdir -p $DIR
cd $DIR

for f in ../*.img*.raw; do
	OLDPFX="$(echo $(basename $f) | sed 's/\.img[0-9][0-9]\.[0-9]\.raw//')"
	NEWFN=$(echo $(basename $f) | sed s/${OLDPFX}/${PFX}/)
	mv $f ./$NEWFN
done
